### ISSUE TITLE
(1.1.1) Build failed

### ISSUE THREAD

**Issue by jakeroam** [yuzushioh/EthereumKit#104]
`	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/jakelaurie/Development/ECDSATest/Carthage/Checkouts/EthereumKit/EthereumKit.xcodeproj -scheme EthereumKit -configuration Release -derivedDataPath /Users/jakelaurie/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/EthereumKit/1.1.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/m9/ngjbz9rs0qq9fbymnkm6r4zh0000gn/T/EthereumKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/jakelaurie/Development/ECDSATest/Carthage/Checkouts/EthereumKit)`

**Comment by yuzushioh** [comment]
related to #106

**Comment by yuzushioh** [comment]
I managed to fix this problem. I will patch it over this weekend. Thank you!

**Comment by yuzushioh** [comment]
this has been fixed in version 1.2.0
