### ISSUE TITLE
Logo Proporsal: EthereumKit

### ISSUE THREAD

**Issue by tjulises** [yuzushioh/EthereumKit#105]
Hey, I'm graphic designer and my aim is supporting open source projects and make my portfolio better. So, I can contribute on your project with making logo design. I am waiting your feedback! Have a nice day! :)

Best Regards,
TJ Ulises
Visual Communication Designer

**Comment by yuzushioh** [comment]
Hi @tjulises thank you for the proposal. I like your aim and what you do to open source projects. What would the logo be like? is there any thoughts in your mind?

**Comment by tjulises** [comment]
Yes I'd like to ask you a few questions to make sure they're printed on the logo...

What's the goal of the project?
What's the message you'd like that the logo transmit
I'm doing my own research about your project too, and see if our ideas matches when it comes to making/choosing a logo :+1:

**Comment by yuzushioh** [comment]
@tjulises Thank you for the replay.

The goal of this project is to make it easier for ios/mobile developer to dive into Ethereum/blockchain space by providing them a framework with an easy-to-understand interface. I hope they try to start building something useful with this framework.

Messages like user-friendly, cool, decentralized would be great.

**Comment by tjulises** [comment]
Hello @yuzushioh , 
This is what I ccame up with :+1: 
I hope you like it,
I'd like to know if you have any suggestions :+1: 
![ethereumkit](https://user-images.githubusercontent.com/39039587/40569519-46bdb1d2-6050-11e8-86ab-25ac504e89a6.png)

**Comment by yuzushioh** [comment]
Hi @tjulises, I like the logo. I like the white one at top right and grey one at bottom left

**Comment by tjulises** [comment]
I personally like the grey one but you lead. Let me know which variation you like most and I'll upload the files

**Comment by yuzushioh** [comment]
Let's go with white one. it gives you an impression of frendly.

The framework logo will be displayed like below. so it would be great if you design the margin and edit README.md, and then submit a Pull Request. let me know if you have any problem

**Comment by tjulises** [comment]
What margin do you mean?
Do you want something to change to the logo? @yuzushioh

**Comment by yuzushioh** [comment]
@tjulises I meant left and right padding by margin. sorry for that. Thank you. I am looking forward to it

**Comment by tjulises** [comment]
![1](https://user-images.githubusercontent.com/39039587/40594985-2cd28ec6-6200-11e8-9f6f-45ae28dfe994.png)
@yuzushioh

**Comment by yuzushioh** [comment]
Hi @tjulises. Thank you for the logo. Should I edit read me with this logo? or are you going to?

**Comment by tjulises** [comment]
Yes @yuzushioh I can update the readme, I could also upload the logo in a folder if you wish, all tho I'll also give you a [google drive](https://drive.google.com/drive/folders/1t9PJp-rInzGF5KZGy-bzyrfrppV8DZzR?usp=sharing) link with all the necessary versions of the logo for any update, thanks for letting me a part of this really cool project :+1:

**Comment by yuzushioh** [comment]
Just one thing, Can I have the logo with text EthereumKit on it? @tjulises
