### ISSUE TITLE
Fix secp256k1 dependency

### ISSUE THREAD

**Issue by yuzushioh** [yuzushioh/EthereumKit#106]

**Comment by yuzushioh** [comment]
@DmitryBespalov @sche Any suggestion for this?

**Comment by maximuskravchenko** [comment]
Hi! I have managed to run app successfully after installing EthereumKit using Carthage 0.23.0.

**Comment by yuzushioh** [comment]
I managed to fix this problem. I will patch it over this weekend.

**Comment by sche** [comment]
Cool! Thanks @yuzushioh

**Comment by yuzushioh** [comment]
this has been fixed in version 1.2.0

**Comment by yuzushioh** [comment]
hmm, that is weird. can you share the repository with me?

**Comment by yuzushioh** [comment]
@MrShafiee I just created new project and install EthereumKit via Carthage. it worked fine. This may be caused by the cache of old frameworks. can you delete everything related to EthereumKit including carthage cache and re-install it?

**Comment by MrShafiee** [comment]
the problem was solved!

**Comment by MrShafiee** [comment]
if anyone else has this error yet, can add secp256k1 library to Carthage file separately:
add this : github "Boilertalk/secp256k1.swift"
and update Carthage file then 👍
