### ISSUE TITLE
Issue with BDouble

### ISSUE THREAD

**Issue by yijiasu** [yuzushioh/EthereumKit#109]
See my debug process:

```
(lldb) po wallet.ether?.description
▿ Optional<String>
  - some : "399979/1000000"

(lldb) po wallet.ether?.decimalExpansion(precisionAfterComma: 4)
▿ Optional<String>
  - some : "0.0000"

(lldb) po wallet.ether?.decimalExpansion(precisionAfterComma: 5)
▿ Optional<String>
  - some : "0.00000"

(lldb) po wallet.ether?.decimalExpansion(precisionAfterComma: 6)
▿ Optional<String>
  - some : "0.399979"

(lldb) po wallet.ether?.decimalExpansion(precisionAfterComma: 8)
▿ Optional<String>
  - some : "0.39997900"
```

wallet.ether is a EthereumKit.BDouble

It's so strange if I do not put enough precision to represent the floating number, it will always return 0.000...

**Comment by yuzushioh** [comment]
Thank you for reporting. This bug is already known. I am thinking about replacing BDouble with Decimal. Wha do you think?

**Comment by yuzushioh** [comment]
I am thinking of deprecating BDouble(Ether) from the project and using Decimal instead. I need to know more about Decimal first, like the max value.
