### ISSUE TITLE
Command /bin/sh failed with exit code 127

### ISSUE THREAD

**Issue by MrShafiee** [yuzushioh/EthereumKit#113]
I got this error after install Cartfile, what should I do?

<img width="864" alt="screen shot 2018-05-23 at 5 56 28 pm" src="https://user-images.githubusercontent.com/19608549/40427375-c3632982-5eb2-11e8-86cc-25dc4586f7c7.png">

**Comment by yuzushioh** [comment]
Installing openssl and secp256k1 has been unstable. I am thinking of how to improve it now. sorry for the inconvenience but could you re-build it. i will work eventually

**Comment by MrShafiee** [comment]
Unfortunately I get this error again :( , and now when I try install carthage packages by terminal I get this error:

<img width="775" alt="screen shot 1397-03-03 at 00 59 14" src="https://user-images.githubusercontent.com/19608549/40449472-c3294e84-5eed-11e8-8746-b755644e5955.png">

and when build project in xcode, Command /bin/sh failed with exit code 127 error appear again.
could you send me necessary packages manually without carthage?

**Comment by yuzushioh** [comment]
is there any reason you are not using the latest Xcode? that error is caused when building crypto swift framework and it seems crypto swift has some kind of bug when compiling swift 4.0.3. About EthereumKit it contains lots of packages so it is not possible to install manually. Could you try again by running `rm -rf ~/Library/Caches/org.carthage.CarthageKit && carthage update --platform ios`?

**Comment by MrShafiee** [comment]
Hi yuzushioh, thanks for your response. I tested it with Xcode 9.3 and 9.4 beta but the results were the same.
and test your command _rm -rf ~/Library/Caches/org.carthage.CarthageKit && carthage update --platform ios_ too but the project was not build and has previous error.

<img width="1158" alt="screen shot 2018-05-24 at 12 45 15 pm copy" src="https://user-images.githubusercontent.com/19608549/40473311-072cecf4-5f51-11e8-8194-21b1c9397d17.png">

**Comment by JinYangZhang** [comment]
I had the same problem.

**Comment by yuzushioh** [comment]
umm, this is weird. I can clean-build in my environment. The log is saying `SDK iphoneos cannot be located`.  After downloading the latest xcode  did you run `xcode-select --switch /Applications/Xcode.app/Contents/Developer/`?

**Comment by yuzushioh** [comment]
if you have multiple xcode in your mac, you need to change the path to switch compiler and stuff

**Comment by yuzushioh** [comment]
I managed to fix this problem. I will patch it over this weekend. Thank you!

**Comment by yuzushioh** [comment]
@MrShafiee this has been fixed in version 1.2.0

**Comment by MrShafiee** [comment]
Thanks @yuzushioh , Same problem here, I found the cause: massive bug in Xcode 👊🏻.

If you ever install a second version of Xcode, Xcode internally disables the command-line tools!

They are still there. You can use them from any command-line. They work perfectly. But ... xcode claims they are missing, because it's scared that you might want to use the old version of the new version.

You have to go into Xcode preferences, go to "Locations" tab, and you'll find the command-line tools dropdown has been wiped, with a note saying "none selected". Select anything, and ... problem goes away. 👍🏻
