### ISSUE TITLE
Updated CryptoSwift to 1.0.0 and dependency version to 9.0

### ISSUE THREAD

**Issue by dmytrostriletskyi** [yuzushioh/EthereumKit#119]
Hello! Thanks a lot for your package, great  job!

Carthage version: `0.29.0`.
Swift version: `4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)`. 
Target: `x86_64-apple-darwin17.5.0`.

But today, after your [changes](https://github.com/yuzushioh/EthereumKit/commit/60378472524073b44125b4bcf1fcd7a61a4462dd#diff-7eba173c347db69674261ade64cfb207), when you updated `CryptoSwift` to `0.10.0` and dependency version to `9.0`, I have the following situation after `carthage update --platform iOS`:

![screen shot 2018-05-30 at 4 13 23 pm](https://user-images.githubusercontent.com/22666467/40730951-a3254c00-6438-11e8-89c8-97697e5d27bf.png)

So dependency was skipped and I cannot to use its [secp256k1](https://github.com/yuzushioh/CryptoEthereumSwift/tree/master/Libraries/secp256k1). 
I tried to use `--no-use-binaries` flag (as Google prompted), then I gave within logs:

```
CryptoEthereumSwift/CryptoEthereumSwift/Source/EllipticCurveEncrypterSecp256k1.swift:2:8:
error: module file's minimum deployment target is ios9.0 v9.0
```

Although I already have 11.3.

I have change `github "krzyzanowskim/CryptoSwift" "0.9.0"` to `github "krzyzanowskim/CryptoSwift" "0.10.0"` in my `Cartfile` directly and all my "installation" problems has expired.

But again, I have the following problem:
```
let wallet: Wallet = Wallet(network: .main, privateKey: privateKey)
compiler error: Type of expression is ambiguous without more context
```

When I change it to the following code:
```
let wallet: Wallet = Wallet(network: .main, privateKey: UserData.privateKey, debugPrints: true)
```

I get:

![screen shot 2018-05-30 at 7 06 33 pm](https://user-images.githubusercontent.com/22666467/40732726-97c8d09e-643c-11e8-80c3-fd5ff06e6566.png)

Can you help me?

**Comment by yuzushioh** [comment]
Hi @dmytrostriletskyi Thank you for the bug report.I will check the dependency problem tomorrow for sure. 

about Carthage skipping `CryptoSwift` , it is totally fine. it skipped to download its pre-built binary because the binary is compiled with older version of swift compiler. It will build locally. In fast `secp256k1` is implemented in `CryptoEthereumSwift` package. (it is still unstable when it comes to building the binary though)

> error: module file's minimum deployment target is ios9.0 v9.0
I believe this is caused because of `CryptoSwift` package's minimum development target. I will fix this asap.

and `Wallet` class, it now has debugPrints parameter to print logs in console. it is required. But Im not sure whats the cause of crash yet. I will look at it later. 

I would like to see more of the codebase if possible to help debug. Thank you.

**Comment by yuzushioh** [comment]
I fixed dependency's minimum development target problem and released v1.2.1. Hopefully it will solve some of the problem. Let me know the error after you update EthereumKit.

**Comment by dmytrostriletskyi** [comment]
@yuzushioh, hi! Thanks for so fast response. 

1) I found that I missed debug window while crashing the application, I just forgot to embed the framework (project setting -> build phases -> embed frameworks):

<img width="647" alt="screen shot 2018-05-30 at 9 27 15 pm" src="https://user-images.githubusercontent.com/22666467/40740036-6863a216-6450-11e8-878a-810b27f65e11.png">
(so this is solved)

**Comment by yuzushioh** [comment]
@dmytrostriletskyi Great 👍 ask me if you have anything. And if you release something with EthereumKit, please add the link to README.md. Thank you.

**Comment by dmytrostriletskyi** [comment]
>> cat Cartfile
```
github "yuzushioh/EthereumKit"
```

>> Cartfile.resolved
github "krzyzanowskim/CryptoSwift" "0.10.0"
github "yuzushioh/CryptoEthereumSwift" "1.0.1"
github "yuzushioh/EthereumKit" "1.2.1"

All problems have resolved! Thanks you a lot, sir @yuzushioh!
Also tested a debugging logs, too tasty and cool! :)

👍 👍
