### ISSUE TITLE
Can I send tokens via your kit?

### ISSUE THREAD

**Issue by Dubickiy** [yuzushioh/EthereumKit#123]
Hi @yuzushioh 

I have question. I need to send Ethereum's tokens (USDT). I know that for sending tokens i must match smart-contract data such as parameter of RawTransaction(field Data). Question: Do you how to resolve that question ?

Thanks

**Comment by yuzushioh** [comment]
Hi @Dubickiy, I am currently working on to support erc20 tokens but i might take some more time to complete. https://github.com/yuzushioh/EthereumKit/pull/102

**Comment by Dubickiy** [comment]
Hi @yuzushioh. How do you think when you finish working with erc20tokens? 

Thanks

Regards

**Comment by topws** [comment]
@yuzushioh  
Urgent need this feature

**Comment by yuzushioh** [comment]
@topws How urgent is that?

**Comment by topws** [comment]
We want to use your library in our project. We have completed the BTC and hopefully you will find time to complete this function.

**Comment by yuzushioh** [comment]
What functions do you need exactly? just transfering erc20 tokens?

**Comment by topws** [comment]
Currently it is

**Comment by yuzushioh** [comment]
Ok i will find some time to work on it

**Comment by topws** [comment]
👍 nice!!!
PS : how long do you think

**Comment by yuzushioh** [comment]
@topws I started to work on it. transfering part is almost done. the rest is fetching a balance of tokens.

**Comment by yuzushioh** [comment]
@Dubickiy @topws See this document 👍 https://github.com/yuzushioh/EthereumKit/blob/master/Documentation/ERC20.md

**Comment by Dubickiy** [comment]
@yuzushioh 
Thank you. Your library is the best !!))

**Comment by topws** [comment]
@yuzushioh when i finished Carthage update, module secp256k1 occured this error --Redefinition of module 'secp256k1' in module.modulemap file;BUT Try it in a new project without error

**Comment by yuzushioh** [comment]
@topws I know that issue. try deleting Build/Checkouts, it will solve the problem. Temporally though

**Comment by topws** [comment]
Can be solved by Removing  the definition of module，I don't know if this is a good solution

**Comment by yuzushioh** [comment]
I will look at it when I have the time!

**Comment by topws** [comment]
If you have time, I hope you can solve keystore......Forgive my excessive request
