### ISSUE TITLE
Blocker. Incorrect Address initialization with String if address starts with 0x0

### ISSUE THREAD

**Issue by maximuskravchenko** [yuzushioh/EthereumKit#126]
public func stripHexPrefix() -> String {
        var hex = self
        while hex.first == "0" || hex.first == "x" {
            hex = String(hex.dropFirst())
        }
        return hex
    }

Method removes not only "0x" at start, but every next "0" prefix. 
So if address is something like "0x0ab1234567..." it returns  "ab1234567...", but should return "0ab1234567...".

**Comment by yuzushioh** [comment]
Thank you for reporting this. this needs to be fixed right now
