### ISSUE TITLE
carthage update  error

### ISSUE THREAD

**Issue by TheCodeor** [yuzushioh/EthereumKit#61]
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/fanpeng/Desktop/teestWallet/Carthage/Checkouts/EthereumKit/EthereumKit.xcodeproj -scheme EthereumKit -configuration Release -derivedDataPath /Users/fanpeng/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/EthereumKit/1.0.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/_l/zg5_vygj6mb_8r9gz_rsvmhr0000gn/T/EthereumKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/fanpeng/Desktop/teestWallet/Carthage/Checkouts/EthereumKit)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/_l/zg5_vygj6mb_8r9gz_rsvmhr0000gn/T/carthage-xcodebuild.y1ltLd.log

**Comment by yuzushioh** [comment]
@TheCodeor Hi! is this problem solved?

**Comment by Weetone** [comment]
Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory

** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution Build\ Libraries /Users/ivan/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/EthereumKit/1.0.0-alpha4/Build/Intermediates.noindex/ArchiveIntermediates/EthereumKit/IntermediateBuildFilesPath/EthereumKit.build/Release-iphoneos/EthereumKit.build/Script-AE8387CD2035DCE100FAC88F.sh
(1 failure)

**Comment by yuzushioh** [comment]
@Weetone could you delete the Carthage cache and try building EthereumKit 1.0.2 again? It should work

**Comment by Weetone** [comment]
Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/ivan/Documents/Wallet/Carthage/Checkouts/EthereumKit/EthereumKit.xcodeproj -scheme EthereumKit -configuration Release -derivedDataPath /Users/ivan/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/EthereumKit/1.0.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/tm/885cp7rs1cl9h4gc1fp7r_tr0000gn/T/EthereumKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/ivan/Documents/Wallet/Carthage/Checkouts/EthereumKit)
