### ISSUE TITLE
transaction error 

### ISSUE THREAD

**Issue by cadaverousblue** [yuzushioh/EthereumKit#87]
JSONRPCError.responseError(code: -32000, message: "insufficient funds for gas * price + value", data: nil)

an error occurred when i  sendrawTransction

**Comment by yuzushioh** [comment]
@cadaverousblue Thank you for the report. I will look deeper at this when I have time.

for quick thought, it might be cased by trying sending the entire balance at once. amount you want to send needs to be less than `amount + (gasLimit * gasPrice)`

**Comment by cadaverousblue** [comment]
i have 1 ETH   and i send  0.0000001 ETH with low gasPrice.

**Comment by yuzushioh** [comment]
@cadaverousblue do you get 1 ETH as well by calling GetBalance request?

**Comment by yuzushioh** [comment]
Okay, i will see whats happening. What is your EthereumKit version you are using?

**Comment by cadaverousblue** [comment]
@yuzushioh 1.0.3

**Comment by yuzushioh** [comment]
do you still have this issue?
