### ISSUE TITLE
secp256k1 module error

### ISSUE THREAD

**Issue by jesuasir007** [yuzushioh/EthereumKit#89]
ya , ethereumkit installation is completed , i have add an ethereumkit module its shows some error,please check me .Missing required module 'secp256k1'

**Comment by yuzushioh** [comment]
Thank you for the report. I will investigate it. I might know the cause.

**Comment by panjiulong** [comment]
I have same problem

**Comment by Dubickiy** [comment]
+ So do I

**Comment by yuzushioh** [comment]
@jesuasir007 @panjiulong I released 1.1.0. could you try updating?

**Comment by maximuskravchenko** [comment]
Hi, I had a problem with secp256k1.
With 1.1.0 there is another problem:

Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/admin/Projects/TESTS/CarthTest/Carthage/Checkouts/EthereumKit/EthereumKit.xcodeproj -scheme EthereumKit -configuration Release -derivedDataPath /Users/admin/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/EthereumKit/1.1.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/7p/9xj8x2dd1qqczd51zlxvgq_w0000gn/T/EthereumKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/admin/Projects/TESTS/CarthTest/Carthage/Checkouts/EthereumKit)

**Comment by yuzushioh** [comment]
related to #106

**Comment by yuzushioh** [comment]
I managed to fix this problem. I will patch it over this weekend. Thank you!

**Comment by yuzushioh** [comment]
this has been fixed in version 1.2.0

**Comment by dujinxin** [comment]
This problem still exists in version 1.2.0,help me !!!

**Comment by yuzushioh** [comment]
@dujinxin clean up everything such as carthage cache or build cache

**Comment by dujinxin** [comment]
@yuzushioh I have tried various ways to solve this problem，and solved this problem by MrShafiee's method, thanks! @MrShafiee
